LANG = {
	// menu
	选择操作: "Menu",
	退出系统: "Exit",
	退出: "Exit",
	系统设置: "Settings",
	登录帐户: "System Account",
	首页: "Home",
	员工: "Employee",
	角色: "Role",
	系统配置: "Conf",
	批量导入: "Import",
	修改密码: "Change Password",
	运营: "Operation",

	// page & dialog
	确定: "OK",
	取消: "Cancel",
	确定后关闭: "CloseAfterOK",
	添加: "Add",
	保存: "Save",
	查询: "Find",
	刷新: "Reload",
	新增: "Add",
	修改: "Set",
	删除: "Del",
	导出: "Export",
	导入: "Import",
	保存查询: "Save Query",
	清除查询: "Clear Query",
	自定义查询: "User Query",
	自定义报表: "User Report",
	报表: "Report",
	统计报表: "Report",
	字段信息: "Field Info",
	数据筛选: "Filter",
	高级查询: "Advanced Query",
	再次新增: "Duplicate Record",
	操作日志: "Object Log",
	查询该字段: "Filter by this field",
	"设置查询名称为? ": "Query Name: ",
	"查询条件(cond)? ": "Query Condition: ",
	"该数据表不支持导入": "This datagrid does not support to import data",
	'逗号分隔(csv)': 'Comma-seperated(csv)',
	'TAB分隔(txt)': 'Tab-seperated(txt)',
	'网页(html)': 'Web page(html)',
	"确定要删除一条记录?": "Delete this record?",
	"删除成功!": "Record is deleted.",
	"请先选择一行。": "No record is selected.",

	"刷新页面": "Reload page",
	"刷新对话框": "Reload dialog",
	"刷新Addon": "Reload addon",
	"批量模式": "Batch mode",
	"关闭其它页": "Close other tabs",
	"关闭右侧页": "Close right-side tabs",

	提示: "Info",
	警告: "Warn",
	出错: "Error",
	确认: "Confirm",
	测试模式: "Test mode",
	模拟模式: "Mock mode",
	"服务器数据错误。": "Bad data format!",
	"服务器通讯协议异常!": "Bad protocol!",
	"操作失败": "Fail",
	"必填项，不可为空": "Mandatary field",
	
	复制本列: "Copy",
	统计本列: "Statistics",
	查询本列: "Query",
	冻结列: "Freeze",

	"操作成功!": "Done!",
	是: "Yes",
	否: "No",
	处理中: "Processing",

	"validate.number": "require a number",
	"validate.idcard": "18-digit idcard",
	"validate.uname": "4-16 chars/digits",
	"validate.pwd": "4-16 chars/digits/symbols",
	"validate.equalTo": "double check fails",
	"validate.cellphone": "require 11-digit phone",
	"validate.datetime": "format: 2010-1-10",
	"validate.usercode": "11-digit phone number, or login name",

	// 登录页
	登录: "Login",
	登录名: "User name",
	密码: "Password",

	// 修改密码
	修改密码: "Change password",
	旧密码: "Old password",
	新密码: "New password",
	确认密码: "Confirm password",
	"密码修改成功!": "Done!",

	// Employee
	编号: "Id",
	手机号: "Phone",
	姓名: "Name",
	登录名: "Uname",
	登录密码: "Password",
	权限: "Permissions",
	最高管理员: "Super Admin",
	管理员: "Admin",

	// General
	运营管理端: "Business System",
	配置名: "Name",
	配置值: "Value",
	名称: "Name",
	权限列表: "Permissions",
	订单: "Order",
	状态: "Status",
	描述: "Description",
	金额: "Amount",
	创建时间: "Create Time",
	对象: "Object",
	操作: "Operation",
	用户: "User",
	日期: "Date",
	时间: "Time",
	明细: "Detail",
	查询结果: "Query Result",
	用户名或密码错误: "Auth fail: bad user name or password"
};
