LANG = {
	提示: "Info",
	警告: "Warn",
	出错: "Error",
	确定: "OK",
	取消: "Cancel",
	添加: "Add",
	保存: "Save",
	查询: "Find",
	刷新: "Reload",
	新增: "Add",
	修改: "Set",
	删除: "Del",
	导出: "Export",
	导入: "Import",
	测试模式: "Test mode",
	模拟模式: "Mock mode",
	"服务器数据错误。": "Bad data format!",
	"服务器通讯协议异常!": "Bad protocol!",
	"操作失败": "Fail",
	手机号或密码错误: "Auth fail: bad phone number or password",
	用户名或密码错误: "Auth fail: bad user name or password",
	
	// page home
	首页: "Home",
	订单列表: "Orders",
	个人信息: "Me",
	订单: "Orders",
	我: "Me"
};
