all:
	cp php/class/AC_Role.php \
		../../php/class/
	cp web/page/pageRole.html \
		web/page/pageRole.js \
		web/page/dlgRole.html \
		web/page/dlgRole.js \
		../../web/page/
sync:
	cp ../../php/class/AC_Role.php \
		php/class/
	cp ../../web/page/pageRole.html \
		../../web/page/pageRole.js \
		../../web/page/dlgRole.html \
		../../web/page/dlgRole.js \
		web/page/
