<?php
/*
jdcloud-gendoc

php gendoc.php mysrc.js -> doc.html
*/

require("lib/common.php");
require("lib/Parsedown.php");

// ====== config
$defaultOptions = [
	"title" => "API文档",
];

// ====== global
$keys = []; # elem:{type, name, ns/namespace}
$newBlock = false;
$blocks = [];
$options = null; # {title, encoding}

// ====== function
// key={type,name}
function makeKeyword($key)
{
	$ns = 'Global';
	if (preg_match('/^(.*)\.(.*)$/', $key['name'], $ms)) {
		$ns = $ms[1];
	}
	else {
	}
	$key['ns'] = $ns;
	return $key;
}

// REFER TO: https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions
class MyParsedown extends Parsedown
{
	function __construct() {
		$this->BlockTypes['@'][] = 'FormatText';
		//$this->inlineMarkerList .= '@';
		$this->breaksEnabled = true;
	}

	protected function blockFormatText($Line)
	{
		$text = $Line['text'];
		if (! preg_match('/@(\w+)\s+([^(){}:? ]+)(.*)/', $text, $ms) )
			return;

		global $newBlock, $keys;
		$class = $ms[1];
		$key = $ms[2];
		$other = $ms[3] ?: "";

		if ($newBlock) {
			$newBlock = false;
			$keys[] = makeKeyword(["name"=>$key, "type"=>$class]);
			$markup = "<h2 id=\"{$key}\">" . $ms[0] . "</h2>"; // remove '@'
		}
		else {
			if ($class == "see") {
				$key = "<a href=\"#{$key}\">{$key}</a>";
			}
			else if ($class == "alias") {
				$keys[] = makeKeyword(["name"=>$key, "type"=>$class]);
				$key = "<a id=\"{$key}\">{$key}</a>";
			}
			$markup = "<p class=\"{$class}\"><strong>@{$class} {$key}</strong> {$other}</p>";
		}
		$Block = [
			"markup" => $markup
		];
		return $Block;
	}

    protected function blockHeader($Line)
	{
		$e = parent::blockHeader($Line);
		$text = $e['element']['name'];
		// 注释中的标题降两级
		if (preg_match('/h(\d+)/', $text, $ms)) {
			$e['element']['name'] = "h" . ((int)$ms[1] + 2);
		}
		return $e;
	}
}

function handleOptionEncoding()
{
	global $options;
	if (@$options['encoding']) {
		foreach (['title'] as $prop) {
			$options[$prop] = iconv($options['encoding'], 'utf-8', $options[$prop]);
		}
	}
}

// ====== main

$argv1 = null;
$options = mygetopt(['title:', 'encoding:'], $argv1) + $defaultOptions;
handleOptionEncoding();
foreach ($argv1 as $f) {
	@$str = file_get_contents($f) or die ("*** require input file.\n");
	$pd = new MyParsedown();

	preg_replace_callback('/
		\/\*\*+\s* (@\w+ \s+ .*?) \s*\*+\/
	/xs', function ($ms) {

		global $newBlock, $pd, $blocks;
		$newBlock = true;
		$blocks[] = $pd->text($ms[1]);

	}, $str);
}

$docDate = date('Y-m-d');
echo <<<EOL
<html>
<head>
<meta charset="utf-8">
<title>{$options['title']}</title>
<link rel="stylesheet" href="style.css" />
</head>

<h1>{$options['title']}</h1>
<div>最后更新：$docDate</div>
<h2>Keywords</h2>

EOL;

usort($keys, function ($a, $b) {
	return strcmp($a['name'], $b['name']);
});
echo "<div>\n";
foreach ($keys as $key) {
	echo "<a href=\"#{$key['name']}\">{$key['name']} ({$key['type']})</a><br>\n";
}
echo "</div><hr>\n";

foreach ($blocks as $s) {
	echo $s;
	echo "<hr>\n";
}


echo "<div style=\"text-align:center\">Generated by jdcloud-gendoc @ " . date('c') . "</div>\n";
echo "</html>";