<html>
<head>
<meta charset="utf-8">
<title><?=Doc::$title?></title>
<style>
h3,h4,h5,h6 {
	font-size: 1em;
}

pre {
	border-left: 1px solid #ccc;
	margin: 0 1em;
	padding: 0 0.5em;
	tab-size:4;
}

code {
	font-family: "Courier New";
    padding: 0px 3px;
    display: inline-block;
}

.toc {
	margin: 2em;
}

.toc p {
	margin: 0.3em 0;
}

.block {
	border-bottom: 1px solid #ccc;
}

</style>
<?php Doc::outputLinkFiles(); ?>
</head>

<body>
<h1><?=Doc::$title?></h1>
<div>最后更新：<?=Doc::$docDate?></div>
<div id="menu">
<?php
Doc::outputModules();
Doc::outputKeys();
?>
</div>
<?php Doc::outputBlocks(); ?>
<div style="text-align:center">Generated by jdcloud-gendoc</div>
</body>

</html>
