all:
	cp m2/page/udt.html \
		m2/page/udt.js \
		../../m2/page/
	cp web/page/pageUDT.html \
		web/page/pageUDT.js \
		web/page/dlgUDT.html \
		web/page/dlgUDT.js \
		../../web/page/
sync:
	cp ../../m2/page/udt.html \
		../../m2/page/udt.js \
		m2/page/
	cp ../../web/page/pageUDT.html \
		../../web/page/pageUDT.js \
		../../web/page/dlgUDT.html \
		../../web/page/dlgUDT.js \
		web/page/
